### ISSUE TITLE
Feature Request Last Update

### ISSUE THREAD

**Issue by Baenker** [Bart1909/ioBroker.netatmo-crawler#1]
Ich fände ein Feld praktisch wo man sieht wann die Daten zuletzt erfolgreich abgeholt wurden (pro Station).

Ob es wirklich nötig ist kann ich nicht beurteilen, da man mittels getState(id).ts ja auch sieht wann das Feld zuletzt verändert wurde. Die Frage wäre dann dort ob bei jeden abholen die Daten überschrieben werden oder nur wenn der Wert sich verändert hat.

Beispiel rain. Wenn es den ganzen Tag nicht regnet müsste das Feld ja nicht immer wieder mit 0 beschrieben werden.  Das würde dann dazu führen dann man mittels getState ein falsches Datum erhalten würde.

Mit einen Datumsfeld wäre es wahrscheinlicher einfacher und auch für weniger erfahrene Nutzer leichter nachvollziehbarer...

**Comment by Bart1909** [comment]
Hi @Baenker ,
aktuell hole ich die Daten ab und speichere diese dann Weg, wenn ich Werte bekomme.
Bekomme ich keine Werte, werden die alten Werte nicht überschrieben und stehen gelassen.
Das bedeutet, getState(id).ts würde sich dann auch nicht ändern, weil ich den Wert nicht aktualisiere, sondern nur, wenn ich einen Wert bekomme.

Ich kann aber gerne noch unter der Station-Info noch ein Feld hinzufügen, wann ich die Werte das letzte Mal erfolgreich abgeholt habe. 

Dir geht es dabei aber nicht um einen Zeitstempel, wann der Wert sich das letzte Mal **geändert** hat, oder? Sondern nur, wann er das letzte Mal erfolgreich ausgelesen wurde, oder?

**Comment by backfisch88** [comment]
Hallo! 

erst mal danke für den Vorschlag!

In IOBroker gibts es die möglichkeit die letzte Änderung für einen Datenpunkt zu Filtern. Damit solltest du ans Ziel kommen.


@Bart1909 da warst du wohl schneller :D

**Comment by Baenker** [comment]
Richtig mir geht es um das letzte Mal erfolgreich ausgelesen. Gerade bei Wackel-Stationen wo die Besitzer vermutlich sein WLAN nicht im Griff hat ist das schon eine Sinnvolle Info. Falls nur ich das so sehe sollte es natürlich nicht umgesetzt werden.

Ich kann mir dazu aber dann auch selber ein Script schreiben. Für mich kein Problem.

**Comment by Bart1909** [comment]
Es gibt in Version 0.3.0 jetzt neue Timestamps:
_netatmo-crawler.0.stationData.**id**.info.lastInfoRetrieved_ gibt an, wann das letzte Mal Werte von der API ausgelesen wurden.
_netatmo-crawler.0.stationData.**id**.lastUpdated.**MeasureName**_ gibt an, wann der Wert zuletzt bei Netatmo aktualisiert wurde (gibt die API mit zurück).
