### ISSUE TITLE
Nur eine Station pro Instanz?

### ISSUE THREAD

**Issue by RK62** [Bart1909/ioBroker.netatmo-crawler#11]
Danke für den Adapter, hat mit einer Station auf Anhieb funktioniert!
Allerdings kann ich keine weiteren Stationen erfassen. 
Wie kann man da weitere Zeilen einblenden?

Gruß, Ralf

![2020-08-13 22_27_47-instances - ioBroker und 2 weitere Seiten - Persönlich – Microsoft​ Edge-ESK01](https://user-images.githubusercontent.com/39200469/90183849-7d0bd280-ddb4-11ea-8f03-076ea462b853.png)

**Comment by Bart1909** [comment]
Hallo Ralf,

schön, dass es auf Anhieb funktioniert hat.
Für eine weitere Station einfach den Cursor hinter den ersten Link setzen und Enter drücken. Dann bekommst du eine neue Zeile und kannst du einen weiteren Link hinzufügen.

Öffnest du die Admin-Seite per Tablet? Bei einem größeren Billdschirm sollte er nämlich eigentlich ein größeres Eingabefeld anzeigen.

Probier es mal aus und gib gerne Rückmeldung, ob es geklappt hat! :-)

**Comment by RK62** [comment]
Ah, ok, so hat es funktioniert.

Ich bin der falschen Hardcopy mit Extrazeilen in der Anleitung aufgesessen:
https://github.com/Bart1909/ioBroker.netatmo-crawler/blob/master/img/insert.jpg

Solltest Du vielleicht noch austauschen.

Danke, Ralf

**Comment by Bart1909** [comment]
Ah stimmt, das ist noch die alte Eingabemaske.
Werde ich ändern!
Danke für den Hinweis!
