### ISSUE TITLE
Error Meldung im Log

### ISSUE THREAD

**Issue by Baenker** [Bart1909/ioBroker.netatmo-crawler#12]
Seit 2 Tagen scheint die Netatmo Station nicht mehr abfragbar zu sein.

Bisher bekam ich die Meldung

warn | (21933) Could not work with station 1 - Message: Did not get any values for station 70:ee:50:12:78:d0
-- | --

Aber seit heute bekomme ich einen Error:

(28550) Error while running Netatmo Crawler. Error Message:No body for authorization token found
--

Wollte nur Fragen ob das ein generelles Problem ist oder ein Einzelproblem?

**Comment by Baenker** [comment]
Habe jetzt auch noch eine andere Station probiert. Gleicher Fehler

**Comment by Bart1909** [comment]
Hi @Baenker,

ja, das ist echt ein Fehler. Hab ich auch gerade gesehen.
Da haben die wohl was auf der Webseite umgestellt.

Ich bau gerade einen Fix! Sollte also hoffentlich gleich ein Update kommen ;-)

**Comment by Bart1909** [comment]
Hi @Baenker,
Version 0.3.5 ist draußen, damit sollte es wieder klappen.
Sollte dann morgen im Repository sein und als Update erscheinen. Ansonsten über Github installieren lassen.

Viele Grüße!

**Comment by Baenker** [comment]
Läuft wieder. Perfekt. Vielen Dank
