### ISSUE TITLE
Fehler "No body for authorization token found"

### ISSUE THREAD

**Issue by RK62** [Bart1909/ioBroker.netatmo-crawler#13]
Habe erfolglos verschiedene Stationen ausprobiert, seit ein paar Tagen erhalte ich die folgende Fehlermeldung:

```
netatmo-crawler.0 | 2020-11-27 13:16:33.843 | info | (9957) Terminated (NO_ERROR): Without reason
netatmo-crawler.0 | 2020-11-27 13:16:33.840 | error | (9957) Error while running Netatmo Crawler. Error Message:No body for authorization token found
netatmo-crawler.0 | 2020-11-27 13:16:33.522 | info | (9957) starting. Version 0.3.4 in /opt/iobroker/node_modules/iobroker.netatmo-crawler, node: v12.19.0, js-controller: 3.1.6
```

Netatmo Crawler 0.3.4
Node.js v12.19.0 
NPM 6.14.8

Gruß, Ralf

**Comment by Bart1909** [comment]
Hi Ralf,

ja, da wurde was umgestellt auf der NetAtmo Webseite.
Es gibt aber auch schon ein Update des Adapters, damit sollte das behoben sein.

Viele Grüße

Tobi

**Comment by RK62** [comment]
Und schon läuft es wieder, Danke!
Solltest das Update für "Stable" freigeben.

Gruß, Ralf

**Comment by Bart1909** [comment]
Perfekt!

Der Adapter muss generell mal in den Stable, aktuell ist der ja nur im Latest.
Sollte ich mal angehen :)
