### ISSUE TITLE
Feature Request rain_yesterday

### ISSUE THREAD

**Issue by Baenker** [Bart1909/ioBroker.netatmo-crawler#2]
Standard mäßig bietet die Netatmo Wetterstation zwei Felder für Regen. Einmal aktuell und einmal kumuliert für den laufenden Tag.

Für die Beurteilung ob bewässert werden muss ist der kumulierte Wert der interessante. Jetzt kann es natürlich passieren, dass es noch regnet wenn man zu Bett geht. Um das zu prüfen bzw in Scripten zu verwenden fände ich es sinnvoll wenn der Inhalt von rain_today jeden neuen Tag in ein neues Feld rain_yesterday schreibt. Gleichzeitig kann man das Feld dann in eine DB speichern um z. B. ein Diagram anzulegen um den tägliche Regenmenge zu loggen. Das Feld müsste nur einmalig am Tagesanfang gefüllt werden.

**Comment by backfisch88** [comment]
Auch hier gibt Blockly die möglichkeit für den vorherigen Wert... der allerdings die Biege macht, wenn es stetig weiter Regnet

**Comment by Bart1909** [comment]
Was noch eine Überlegung wäre, dass man den Wert über die API abfragt.
Ich schau mir das gerade mal an, aber man sollte den Wert für den Vortag auch abfragen können

**Comment by Baenker** [comment]
@backfisch88 der vorherige Wert ist etwas ganz anderes. Nehmen wir das Feld rain_today. Dieser Wert kann sich mit jeder Abfrage ändern, da es ja die Regenmenge vom gesamten Tag abbildet. Somit kann ich den vorherigen Wert natürlich mit der ersten Abfrage am neuen Tag abfragen (nur dort ist er ja relevant). Alternativ kann ich auch den aktuellen Wert um 23:59 abfragen und in ein eigenes Datenfeld schreiben. Beides mal muss der User ein eigenes Feld erstellen und ein eigenes Script schreiben. So muss aber jeder sich etwas ausdenken und programmieren. Wenn es im Adapter ist muss es nur einer. Den Aufwand halte ich für relativ gering, da es nur ein paar Zeilen Code sind wovon jeder User profitiert.

Falls der Wert Abfragbar wäre, wäre das natürlich gut aber ich glaube das geht bei den öffentlichen Daten nicht. Ansonsten gibt es noch sehr viele Felder die Netatmo hat die sehr interessant sind :-)

Wie schon geschrieben wenn es nicht umgesetzt wird, finde ich es nicht tragisch.

**Comment by Bart1909** [comment]
Ist in der Version 0.3.0 enthalten. Wert bekomm ich über die API zurück
