### ISSUE TITLE
Could not get Rain Today for station ...

### ISSUE THREAD

**Issue by Diginix** [Bart1909/ioBroker.netatmo-crawler#21]
every day at 0 o clock I get multiple times these log warnings:

> 2021-07-19 00:00:06.127 - warn: netatmo-crawler.0 (1931233) Could not get Rain Today for station 70:ee:50:65:37:e8: TypeError: Cannot read property 'value' of undefined
> 2021-07-19 00:00:07.435 - warn: netatmo-crawler.0 (1931233) Could not get Rain Today for station 70:ee:50:65:37:e8: TypeError: Cannot read property 'value' of undefined
> 2021-07-19 00:01:02.699 - warn: netatmo-crawler.0 (1931483) Could not get Rain Today for station 70:ee:50:65:37:e8: TypeError: Cannot read property 'value' of undefined
> 2021-07-19 00:01:03.921 - warn: netatmo-crawler.0 (1931483) Could not get Rain Today for station 70:ee:50:65:37:e8: TypeError: Cannot read property 'value' of undefined
> 2021-07-19 00:02:01.986 - warn: netatmo-crawler.0 (1931617) Could not get Rain Today for station 70:ee:50:65:37:e8: TypeError: Cannot read property 'value' of undefined
> 2021-07-19 00:02:03.220 - warn: netatmo-crawler.0 (1931617) Could not get Rain Today for station 70:ee:50:65:37:e8: TypeError: Cannot read property 'value' of undefined
> 2021-07-19 00:03:02.064 - warn: netatmo-crawler.0 (1931762) Could not get Rain Today for station 70:ee:50:65:37:e8: TypeError: Cannot read property 'value' of undefined
> 2021-07-19 00:03:03.319 - warn: netatmo-crawler.0 (1931762) Could not get Rain Today for station 70:ee:50:65:37:e8: TypeError: Cannot read property 'value' of undefined
> 2021-07-19 00:04:02.088 - warn: netatmo-crawler.0 (1931879) Could not get Rain Today for station 70:ee:50:65:37:e8: TypeError: Cannot read property 'value' of undefined
> 2021-07-19 00:04:03.386 - warn: netatmo-crawler.0 (1931879) Could not get Rain Today for station 70:ee:50:65:37:e8: TypeError: Cannot read property 'value' of undefined
> 2021-07-19 00:05:01.882 - warn: netatmo-crawler.0 (1932017) Could not get Rain Today for station 70:ee:50:65:37:e8: TypeError: Cannot read property 'value' of undefined
> 2021-07-19 00:05:03.154 - warn: netatmo-crawler.0 (1932017) Could not get Rain Today for station 70:ee:50:65:37:e8: TypeError: Cannot read property 'value' of undefined
> 2021-07-19 00:06:01.946 - warn: netatmo-crawler.0 (1932184) Could not get Rain Today for station 70:ee:50:65:37:e8: TypeError: Cannot read property 'value' of undefined
> 2021-07-19 00:06:03.172 - warn: netatmo-crawler.0 (1932184) Could not get Rain Today for station 70:ee:50:65:37:e8: TypeError: Cannot read property 'value' of undefined
> 2021-07-19 00:07:01.947 - warn: netatmo-crawler.0 (1932321) Could not get Rain Today for station 70:ee:50:65:37:e8: TypeError: Cannot read property 'value' of undefined
> 2021-07-19 00:07:03.189 - warn: netatmo-crawler.0 (1932321) Could not get Rain Today for station 70:ee:50:65:37:e8: TypeError: Cannot read property 'value' of undefined
> 2021-07-19 00:08:01.970 - warn: netatmo-crawler.0 (1932441) Could not get Rain Today for station 70:ee:50:65:37:e8: TypeError: Cannot read property 'value' of undefined
> 2021-07-19 00:08:03.201 - warn: netatmo-crawler.0 (1932441) Could not get Rain Today for station 70:ee:50:65:37:e8: TypeError: Cannot read property 'value' of undefined

This happens for every station if it is more than one.
NodeJS 12.22.2
JS-Controller 3.3.14
Admin 5.1.12

**Comment by Bart1909** [comment]
Hi @Diginix,

this can happen, if the Netatmo service is not responding. This happens sometimes, when there is a lot of traffic or there are changes (at least that's what I assume).
The adapter then writes a warning, to show, that the data could not be found - this is not really an error. 
If this happens infrequent, this is "normal". Only, if this happens multiple times in a row, it can indicate, that there is an error with the station or the connection to the netatmo servers.

Best wishes

Tobi

**Comment by Diginix** [comment]
It happens always every day 0 o clock for all stations and for each station multiple log entries until up to 10 minutes.
So, it has nothing to do with a dedicated station. The days I had 4 stations in my setup, I got the warnings for all 4.
The adapter runs once per minute, but the warnings appears again after seconds.

> 2021-07-17 00:00:05.846 - warn: netatmo-crawler.0 (1514105) Could not get Rain Today for station 70:ee:50:65:37:e8: TypeError: Cannot read property 'value' of undefined
> 2021-07-17 00:00:07.178 - warn: netatmo-crawler.0 (1514105) Could not get Rain Today for station 70:ee:50:65:37:e8: TypeError: Cannot read property 'value' of undefined
> 2021-07-17 00:01:01.993 - warn: netatmo-crawler.0 (1514354) Could not get Rain Today for station 70:ee:50:65:37:e8: TypeError: Cannot read property 'value' of undefined
> 2021-07-17 00:01:03.222 - warn: netatmo-crawler.0 (1514354) Could not get Rain Today for station 70:ee:50:65:37:e8: TypeError: Cannot read property 'value' of undefined
> 2021-07-17 00:02:01.981 - warn: netatmo-crawler.0 (1514502) Could not get Rain Today for station 70:ee:50:65:37:e8: TypeError: Cannot read property 'value' of undefined
> 2021-07-17 00:02:03.230 - warn: netatmo-crawler.0 (1514502) Could not get Rain Today for station 70:ee:50:65:37:e8: TypeError: Cannot read property 'value' of undefined
> 2021-07-17 00:03:01.872 - warn: netatmo-crawler.0 (1514623) Could not get Rain Today for station 70:ee:50:65:37:e8: TypeError: Cannot read property 'value' of undefined
> 2021-07-17 00:03:03.108 - warn: netatmo-crawler.0 (1514623) Could not get Rain Today for station 70:ee:50:65:37:e8: TypeError: Cannot read property 'value' of undefined
> 2021-07-17 00:04:01.868 - warn: netatmo-crawler.0 (1514757) Could not get Rain Today for station 70:ee:50:65:37:e8: TypeError: Cannot read property 'value' of undefined
> 2021-07-17 00:04:03.120 - warn: netatmo-crawler.0 (1514757) Could not get Rain Today for station 70:ee:50:65:37:e8: TypeError: Cannot read property 'value' of undefined
> 2021-07-17 00:05:02.093 - warn: netatmo-crawler.0 (1514913) Could not get Rain Today for station 70:ee:50:65:37:e8: TypeError: Cannot read property 'value' of undefined
> 2021-07-17 00:05:03.311 - warn: netatmo-crawler.0 (1514913) Could not get Rain Today for station 70:ee:50:65:37:e8: TypeError: Cannot read property 'value' of undefined
> 2021-07-17 00:06:01.860 - warn: netatmo-crawler.0 (1515055) Could not get Rain Today for station 70:ee:50:65:37:e8: TypeError: Cannot read property 'value' of undefined
> 2021-07-17 00:06:03.121 - warn: netatmo-crawler.0 (1515055) Could not get Rain Today for station 70:ee:50:65:37:e8: TypeError: Cannot read property 'value' of undefined
> 2021-07-17 00:07:01.947 - warn: netatmo-crawler.0 (1515178) Could not get Rain Today for station 70:ee:50:65:37:e8: TypeError: Cannot read property 'value' of undefined
> 2021-07-17 00:07:03.208 - warn: netatmo-crawler.0 (1515178) Could not get Rain Today for station 70:ee:50:65:37:e8: TypeError: Cannot read property 'value' of undefined
> 2021-07-17 00:08:02.000 - warn: netatmo-crawler.0 (1515318) Could not get Rain Today for station 70:ee:50:65:37:e8: TypeError: Cannot read property 'value' of undefined
> 2021-07-17 00:08:03.182 - warn: netatmo-crawler.0 (1515318) Could not get Rain Today for station 70:ee:50:65:37:e8: TypeError: Cannot read property 'value' of undefined
> 2021-07-17 00:09:01.975 - warn: netatmo-crawler.0 (1515465) Could not get Rain Today for station 70:ee:50:65:37:e8: TypeError: Cannot read property 'value' of undefined
> 2021-07-17 00:09:03.168 - warn: netatmo-crawler.0 (1515465) Could not get Rain Today for station 70:ee:50:65:37:e8: TypeError: Cannot read property 'value' of undefined
> 2021-07-17 00:10:02.107 - warn: netatmo-crawler.0 (1515585) Could not get Rain Today for station 70:ee:50:65:37:e8: TypeError: Cannot read property 'value' of undefined
> 2021-07-17 00:10:03.378 - warn: netatmo-crawler.0 (1515585) Could not get Rain Today for station 70:ee:50:65:37:e8: TypeError: Cannot read property 'value' of undefined
> 
> 2021-07-18 00:00:04.820 - warn: netatmo-crawler.0 (1722261) Could not get Rain Today for station 70:ee:50:65:37:e8: TypeError: Cannot read property 'value' of undefined
> 2021-07-18 00:00:06.061 - warn: netatmo-crawler.0 (1722261) Could not get Rain Today for station 70:ee:50:65:37:e8: TypeError: Cannot read property 'value' of undefined
> 2021-07-18 00:01:01.951 - warn: netatmo-crawler.0 (1722522) Could not get Rain Today for station 70:ee:50:65:37:e8: TypeError: Cannot read property 'value' of undefined
> 2021-07-18 00:01:03.182 - warn: netatmo-crawler.0 (1722522) Could not get Rain Today for station 70:ee:50:65:37:e8: TypeError: Cannot read property 'value' of undefined
> 
> 2021-07-19 00:00:06.127 - warn: netatmo-crawler.0 (1931233) Could not get Rain Today for station 70:ee:50:65:37:e8: TypeError: Cannot read property 'value' of undefined
> 2021-07-19 00:00:07.435 - warn: netatmo-crawler.0 (1931233) Could not get Rain Today for station 70:ee:50:65:37:e8: TypeError: Cannot read property 'value' of undefined
> 2021-07-19 00:01:02.699 - warn: netatmo-crawler.0 (1931483) Could not get Rain Today for station 70:ee:50:65:37:e8: TypeError: Cannot read property 'value' of undefined
> 2021-07-19 00:01:03.921 - warn: netatmo-crawler.0 (1931483) Could not get Rain Today for station 70:ee:50:65:37:e8: TypeError: Cannot read property 'value' of undefined
> 2021-07-19 00:02:01.986 - warn: netatmo-crawler.0 (1931617) Could not get Rain Today for station 70:ee:50:65:37:e8: TypeError: Cannot read property 'value' of undefined
> 2021-07-19 00:02:03.220 - warn: netatmo-crawler.0 (1931617) Could not get Rain Today for station 70:ee:50:65:37:e8: TypeError: Cannot read property 'value' of undefined
> 2021-07-19 00:03:02.064 - warn: netatmo-crawler.0 (1931762) Could not get Rain Today for station 70:ee:50:65:37:e8: TypeError: Cannot read property 'value' of undefined
> 2021-07-19 00:03:03.319 - warn: netatmo-crawler.0 (1931762) Could not get Rain Today for station 70:ee:50:65:37:e8: TypeError: Cannot read property 'value' of undefined
> 2021-07-19 00:04:02.088 - warn: netatmo-crawler.0 (1931879) Could not get Rain Today for station 70:ee:50:65:37:e8: TypeError: Cannot read property 'value' of undefined
> 2021-07-19 00:04:03.386 - warn: netatmo-crawler.0 (1931879) Could not get Rain Today for station 70:ee:50:65:37:e8: TypeError: Cannot read property 'value' of undefined
> 2021-07-19 00:05:01.882 - warn: netatmo-crawler.0 (1932017) Could not get Rain Today for station 70:ee:50:65:37:e8: TypeError: Cannot read property 'value' of undefined
> 2021-07-19 00:05:03.154 - warn: netatmo-crawler.0 (1932017) Could not get Rain Today for station 70:ee:50:65:37:e8: TypeError: Cannot read property 'value' of undefined
> 2021-07-19 00:06:01.946 - warn: netatmo-crawler.0 (1932184) Could not get Rain Today for station 70:ee:50:65:37:e8: TypeError: Cannot read property 'value' of undefined
> 2021-07-19 00:06:03.172 - warn: netatmo-crawler.0 (1932184) Could not get Rain Today for station 70:ee:50:65:37:e8: TypeError: Cannot read property 'value' of undefined
> 2021-07-19 00:07:01.947 - warn: netatmo-crawler.0 (1932321) Could not get Rain Today for station 70:ee:50:65:37:e8: TypeError: Cannot read property 'value' of undefined
> 2021-07-19 00:07:03.189 - warn: netatmo-crawler.0 (1932321) Could not get Rain Today for station 70:ee:50:65:37:e8: TypeError: Cannot read property 'value' of undefined
> 2021-07-19 00:08:01.970 - warn: netatmo-crawler.0 (1932441) Could not get Rain Today for station 70:ee:50:65:37:e8: TypeError: Cannot read property 'value' of undefined
> 2021-07-19 00:08:03.201 - warn: netatmo-crawler.0 (1932441) Could not get Rain Today for station 70:ee:50:65:37:e8: TypeError: Cannot read property 'value' of undefined

**Comment by Bart1909** [comment]
Okay, got it.
I think, this is because I try to get the summarized value for todays rain from netatmo. But the first minutes of the new day, there seems to be no value being returned.
I will mute this warning respectively setting it to debug.

**Comment by Diginix** [comment]
Perfect. I think it should delayed or muted at least until 00:15. In the hope that all stations sends its values more often than every 15 minutes.

**Comment by Bart1909** [comment]
Is implemented in version 0.5.1 - This will be available in the latest branch in the next hours. Please try, if this works for you :)
