### ISSUE TITLE
all objects read only and written values with ack flag

### ISSUE THREAD

**Issue by Diginix** [Bart1909/ioBroker.netatmo-crawler#23]
At the moment all objects are read and writeable. Usually such objects should be read only and the adapter should write all values with ack flag (acknowledge).
https://github.com/ioBroker/ioBroker/wiki/Adapter-Development-Documentation#commands-and-statuses

**Comment by Bart1909** [comment]
implemented in version 0.6.0

**Comment by Diginix** [comment]
All objects are writeable for me with 0.6.0:
`"write": true,`
Do I have to delete all station objects to force the adapter to create it new?

**Comment by Diginix** [comment]
Even with 0.6.3 all states are still writeable.

**Comment by Bart1909** [comment]
Please try 0.7.1 - You also have to delete the station objects and let the adapter create them new

**Comment by Diginix** [comment]
All states are now read only. Thanks
