### ISSUE TITLE
Confirm data points with ack = true

### ISSUE THREAD

**Issue by Xenon-s** [Bart1909/ioBroker.netatmo-crawler#26]
**Describe the bug**  
Hello and thanks for the cool adapter! But I have a question (I'm an adapter developer myself): Why don't you confirm your values with ack = true? I only respond to ack = true by default in scripts, since it is the default when an adapter writes its own values to datapoints.

**Expected behavior**  
 I think you should fix that with a future update.

**Screenshots & Logfiles**  
![github issue](https://user-images.githubusercontent.com/65488191/130394755-0139e7f5-47bf-4062-bd93-48c90f7b7a9a.png)

**Versions:**  
 - Adapter version: <0.5.1>

**Comment by Bart1909** [comment]
implemented in version 0.6.0 - thank you very much @Xenon-s
