### ISSUE TITLE
Only one station insertable?

### ISSUE THREAD

**Issue by Xenon-s** [Bart1909/ioBroker.netatmo-crawler#27]
**Describe the bug**  
It looks like you can only insert one station.

**To Reproduce**  
1. Go to 'GUI' -> Only one line for station link

**Expected behavior**  
Please adjust the documentation or just provide multiple lines for input. The coolest thing would be a "+" button to add new lines. (table2value and value2table function is provided by ioBroker to create simple tables ;-) ).

**Screenshots & Logfiles**  
**My GUI (Admin 5.1.25)**
![github issue](https://user-images.githubusercontent.com/65488191/130395840-caac398c-3d33-48d9-aa6a-18f194cecb3d.png)

**GUI Doku:**
![doku github](https://user-images.githubusercontent.com/65488191/130395871-39cb7599-b829-4105-889b-6800def6e389.png)

**Versions:**  
 - Adapter version: <0.5.1>
 - JS-Controller version: <3.3.15>
 - Node version: <14.17.5> 
 - Operating system: <Ubuntu 20.04>

**Comment by Bart1909** [comment]
Updated documentation with current screenshot. 
The rebuild of the frontend is on my to-do list, but I've no timetable, when this will be available
