### ISSUE TITLE
Kann Stationen mit Regendaten nicht auslesen

### ISSUE THREAD

**Issue by tazilo815** [Bart1909/ioBroker.netatmo-crawler#3]
**Describe the bug**  
Sobald ich in der Liste eine Station mit Regensensor aufnehme, brechen die Abfragen beim crawlen mit einer Error meldung ab. Alle nachstehenden Stationen werden nicht abgefragt.
Sind in der Liste nur Stationen ohne Regensensor, klappt das abfragen

Auszug aus der Logfile:

host.IOBroker | 2020-07-02 14:40:12.155 | info | instance system.adapter.netatmo-crawler.0 terminated with code 0 (NO_ERROR)
-- | -- | -- | --
netatmo-crawler.0 | 2020-07-02 14:40:11.639 | info | (420) Terminated (NO_ERROR): Without reason
netatmo-crawler.0 | 2020-07-02 14:40:11.638 | info | (420) terminating
netatmo-crawler.0 | 2020-07-02 14:40:11.636 | error | (420) TypeError: Cannot read property 'value' of undefined at Request._callback (/opt/iobroker/node_modules/iobroker.netatmo-crawler/main.js:365:56) at Request.self.callback (/opt/iobroker/nod
netatmo-crawler.0 | 2020-07-02 14:40:11.636 | error | (420) unhandled promise rejection: Cannot read property 'value' of undefined
netatmo-crawler.0 | 2020-07-02 14:40:11.635 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
netatmo-crawler.0 | 2020-07-02 14:40:11.424 | info | (420) Saving station data for station: 1
netatmo-crawler.0 | 2020-07-02 14:40:11.250 | info | (420) Getting data for stationid:70:ee:50:20:80:f2
netatmo-crawler.0 | 2020-07-02 14:40:11.249 | info | (420) Going to get information for station: 1
netatmo-crawler.0 | 2020-07-02 14:40:09.278 | info | (420) config stationNameType: counter
netatmo-crawler.0 | 2020-07-02 14:40:09.278 | info | (420) config stationUrls: https://weathermap.netatmo.com//?zoom=15&type=temp&param=Filter&stationid=70%3Aee%3A50%3A20%3A80%3Af2&maplayer=Map&lang=undefined
netatmo-crawler.0 | 2020-07-02 14:40:09.270 | info | (420) starting. Version 0.3.0 in /opt/iobroker/node_modules/iobroker.netatmo-crawler, node: v12.16.3, js-controller: 3.1.4
host.IOBroker | 2020-07-02 14:40:08.835 | info | instance system.adapter.netatmo-crawler.0 started with pid 420
host.IOBroker | 2020-07-02 14:40:08.824 | info | instance scheduled system.adapter.netatmo-crawler.0 */5 * * * *

**Comment by Bart1909** [comment]
Hi @tazilo815 ,
ich habe die Station gerade mal bei mir ausprobiert, da funktioniert es.
Ich habe aber gerade die Version 0.3.1 bereitgestellt, wo die Fehlerbehandlung optimiert wurde.
Jetzt sollte er zumindest die weiteren Stationen anschließend auslesen, wenn ein Fehler aufgetreten ist.
Du könntest dann auch gerne den Adapter mal auf Debug-Level stellen und dann nochmal die Logausgabe hier posten

**Comment by tazilo815** [comment]
Hallo @Bart1909 
Ich habe das Loglevel auf Debug gestellt:


host.IOBroker | 2020-07-02 16:13:12.201 | info | instance system.adapter.netatmo-crawler.0 terminated with code 0 (NO_ERROR)
-- | -- | -- | --
netatmo-crawler.0 | 2020-07-02 16:13:11.692 | info | (26353) Terminated (NO_ERROR): Without reason
netatmo-crawler.0 | 2020-07-02 16:13:11.692 | info | (26353) terminating
netatmo-crawler.0 | 2020-07-02 16:13:11.689 | error | (26353) TypeError: Cannot read property 'value' of undefined at Request._callback (/opt/iobroker/node_modules/iobroker.netatmo-crawler/main.js:365:56) at Request.self.callback (/opt/iobroker/n
netatmo-crawler.0 | 2020-07-02 16:13:11.689 | error | (26353) unhandled promise rejection: Cannot read property 'value' of undefined
netatmo-crawler.0 | 2020-07-02 16:13:11.689 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
netatmo-crawler.0 | 2020-07-02 16:13:11.688 | debug | (26353) Body Rain_Today:[]
netatmo-crawler.0 | 2020-07-02 16:13:11.497 | debug | (26353) Saving data for station: 1 and measure: rain
netatmo-crawler.0 | 2020-07-02 16:13:11.494 | debug | (26353) Saving data for station: 1 and measure: temperature
netatmo-crawler.0 | 2020-07-02 16:13:11.485 | info | (26353) Saving station data for station: 1
netatmo-crawler.0 | 2020-07-02 16:13:11.485 | debug | (26353) Body:[{"_id":"70:ee:50:20:80:f2","place":{"location":[8.654191,49.213574],"timezone":"Europe/Berlin","country":"DE","altitude":126,"city":"Bad Schönborn","street":"Otfried-Preußler-Ring"},"mar
netatmo-crawler.0 | 2020-07-02 16:13:11.339 | info | (26353) Getting data for stationid:70:ee:50:20:80:f2
netatmo-crawler.0 | 2020-07-02 16:13:11.338 | info | (26353) Going to get information for station: 1
netatmo-crawler.0 | 2020-07-02 16:13:11.338 | debug | (26353) Working with stationUrl: https://weathermap.netatmo.com//?zoom=15&type=temp&param=Filter&stationid=70%3Aee%3A50%3A20%3A80%3Af2&maplayer=Map&lang=undefined
netatmo-crawler.0 | 2020-07-02 16:13:11.338 | debug | (26353) Token:Bearer 52d42bfc1777599b298b456c\|4b157f5a32cd79d1b46d4fb4a2ff10a0
netatmo-crawler.0 | 2020-07-02 16:13:10.654 | info | (26353) config stationNameType: counter
netatmo-crawler.0 | 2020-07-02 16:13:10.654 | info | (26353) config stationUrls: https://weathermap.netatmo.com//?zoom=15&type=temp&param=Filter&stationid=70%3Aee%3A50%3A20%3A80%3Af2&maplayer=Map&lang=undefined
netatmo-crawler.0 | 2020-07-02 16:13:10.646 | info | (26353) starting. Version 0.3.0 in /opt/iobroker/node_modules/iobroker.netatmo-crawler, node: v12.16.3, js-controller: 3.1.4
host.IOBroker | 2020-07-02 16:13:10.160 | info | instance system.adapter.netatmo-crawler.0 started with pid 26353
host.IOBroker | 2020-07-02 16:13:10.148 | info | instance scheduled system.adapter.netatmo-crawler.0 */5 * * * *
host.IOBroker | 2020-07-02 16:13:07.137 | info | stopInstance system.adapter.netatmo-crawler.0 (force=false, process=false)
host.IOBroker | 2020-07-02 16:13:07.137 | info | "system.adapter.netatmo-crawler.0" enabled

**Comment by Bart1909** [comment]
Sehr seltsam @tazilo815 , weil ich die Werte ausgelesen bekomme :-/
Kannst du vielleicht mal die neueste Version 0.3.1 installieren?
Damit sollte er dann zumindest nicht mehr abbrechen,  wenn er dort auf nen Fehler läuft

**Comment by DavidPasch** [comment]
Hab das selbe Problem, allerdings nur zwischen 0:00 und ca. 1:00. Läuft ansonsten super durch, nur eben in dem Zeitraum nicht. Habe 3.2 installiert, beobachte.

**Comment by Bart1909** [comment]
Hi @DavidPasch ,
hattest du das Problem diese Nacht wieder? Und wenn ja, mit welcher Version?
Könntest du dann bitte auch die Logdateien von diesem Zeitraum einfügen? :-)

**Comment by DavidPasch** [comment]
Hi @Bart1909,

interessanterweise nicht zwischen 0:00 und 1:00 ... lief alles glatt.

Habe gegen 9:00 den Fehler gehabt - einmalig.

netatmo-crawler.0 | 2020-07-04 09:00:20.146 | error | at processTicksAndRejections (internal/process/task_queues.js:84:21)
-- | -- | -- | --
netatmo-crawler.0 | 2020-07-04 09:00:20.146 | error | at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
netatmo-crawler.0 | 2020-07-04 09:00:20.146 | error | at emitErrorNT (internal/streams/destroy.js:92:8)
netatmo-crawler.0 | 2020-07-04 09:00:20.146 | error | at TLSSocket.emit (events.js:315:20)
netatmo-crawler.0 | 2020-07-04 09:00:20.146 | error | at TLSSocket.socketErrorListener (_http_client.js:426:9)
netatmo-crawler.0 | 2020-07-04 09:00:20.146 | error | at ClientRequest.emit (events.js:315:20)
netatmo-crawler.0 | 2020-07-04 09:00:20.146 | error | at Request.onRequestError (/opt/iobroker/node_modules/request/request.js:877:8)
netatmo-crawler.0 | 2020-07-04 09:00:20.146 | error | at Request.emit (events.js:315:20)
netatmo-crawler.0 | 2020-07-04 09:00:20.146 | error | at self.callback (/opt/iobroker/node_modules/request/request.js:185:22)
netatmo-crawler.0 | 2020-07-04 09:00:20.146 | error | at Request._callback (/opt/iobroker/node_modules/iobroker.netatmo-crawler/main.js:249:40)
netatmo-crawler.0 | 2020-07-04 09:00:20.146 | error | (13120) TypeError: Cannot read property 'match' of undefined
netatmo-crawler.0 | 2020-07-04 09:00:20.145 | error | (13120) unhandled promise rejection: Cannot read property 'match' of undefined
Unhandled | 2020-07-04 09:00:20.145 | error | promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
netatmo-crawler.0 | 2020-07-04 09:00:20.144 | error | (13120) Error while running Netatmo Crawler. Error Message:Error: getaddrinfo EAI_AGAIN weathermap.netatmo.com
netatmo-crawler.0 | 2020-07-04 09:00:20.139 | error | (13120) Error: Error: getaddrinfo EAI_AGAIN weathermap.netatmo.com

Gefühlt ist allerdings unsere Internet-Leitung etwas stotterig die letzten Tage - nicht das genau um 9:00 keine Connection da war. Ich beobachte das mal weiter.

**Comment by Bart1909** [comment]
Okay, da steigt er ganz am Anfang aus, konnte also die Webseite von Netatmo gar nicht erreichen.
Also entweder war die Webseite von denen nicht erreichbar, oder deine Internetverbindung war wirklich weg zu dem Zeitpunkt.
Werde den Fehler aber auch noch behandeln, damit da kein Abbruch kommt

**Comment by Bart1909** [comment]
So, Version 0.3.4 ist draußen. Damit sollten jetzt alle Fehler behandelt werden und "vernünftig" rausgeschrieben werden

**Comment by DavidPasch** [comment]
0.3.4. wirft soweit keine Errors mehr. Sieht also gut aus!
