### ISSUE TITLE
rain_yesterday gleicher Wert wie rain_today

### ISSUE THREAD

**Issue by Baenker** [Bart1909/ioBroker.netatmo-crawler#4]
Habe gerade Version 0.3.1 installiert. Der neue Datenpunkt wurde angelegt. Leider passt es von den Daten nicht.

Gestern als ich ins Bett ging hatte rain_today einen Wert von über 18ml. Somit hätte ich erwartet das der rain_yesterday einen Wert über diesen 18ml haben müsste, da es dort noch kräftig am regnen war. Leider zeigt der Wert nur eine 0,1 an. Das ist zufällig genau der Wert von rain_today. Ich beobachte es mal weiter was der Wert Morgen sagt. 

Morgen soll es bei uns trocken sein. Gerade regnet es.

**Comment by Bart1909** [comment]
Hi @Baenker,
kannst du mir die StationId mal schicken?

**Comment by Baenker** [comment]
70:ee:50:12:78:d0

https://weathermap.netatmo.com//?zoom=12&type=rain&param=hourly&stationid=70%3Aee%3A50%3A12%3A78%3Ad0&maplayer=Map&lang=undefined

**Comment by Bart1909** [comment]
Also über die API bekomme ich einen Wert von 21,3mm für gestern und 0.5mm für heute raus.

Ist die Uhrzeit auf deinem System, wo ioBroker läuft richtig eingestellt?

Werde morgen mal ne Debug Ausgabe einbauen, welchen Zeitraum er abfragt

**Comment by Baenker** [comment]
21,3 gestern würde passen. 0,5 kann auch stimmen. Eben war es 0,1 und dann fing es an zu regnen.

Uhrzeit auf dem System paßt. Habe gerade die Daten nochmal abgerufen. Jetzt stehen beide Felder auf 0,5

**Comment by Bart1909** [comment]
Kannst du mal dein Loglevel auf Debug stellen und die Ausgabe von einem kompletten „Lauf“ mal hier posten?

**Comment by Baenker** [comment]
host.iobroker_V41 | 2020-07-02 19:25:52.196 | info | instance system.adapter.netatmo-crawler.0 terminated with code 0 (NO_ERROR)
-- | -- | -- | --
netatmo-crawler.0 | 2020-07-02 19:25:51.674 | info | (23403) Terminated (NO_ERROR): Without reason
netatmo-crawler.0 | 2020-07-02 19:25:51.672 | debug | (23403) all done, exiting
netatmo-crawler.0 | 2020-07-02 19:25:51.623 | debug | (23403) Saving data for station: 70:ee:50:12:78:d0 and measure: humidity
netatmo-crawler.0 | 2020-07-02 19:25:51.574 | debug | (23403) Saving data for station: 70:ee:50:12:78:d0 and measure: pressure
netatmo-crawler.0 | 2020-07-02 19:25:51.529 | debug | (23403) Saved rain_yesterday for station: 70:ee:50:12:78:d0
netatmo-crawler.0 | 2020-07-02 19:25:51.383 | debug | (23403) Rain Yesterday for Station 70:ee:50:12:78:d0 is: 21.3
netatmo-crawler.0 | 2020-07-02 19:25:51.382 | debug | (23403) Body Rain_Yesterday:[{"beg_time":1593554400,"value":[[21.3]]}]
netatmo-crawler.0 | 2020-07-02 19:25:51.161 | debug | (23403) Saved rain_today for station: 70:ee:50:12:78:d0
netatmo-crawler.0 | 2020-07-02 19:25:51.115 | debug | (23403) Rain Today for Station 70:ee:50:12:78:d0 is: 0.5
netatmo-crawler.0 | 2020-07-02 19:25:51.115 | debug | (23403) Body Rain_Today:[{"beg_time":1593640800,"value":[[0.5]]}]
netatmo-crawler.0 | 2020-07-02 19:25:50.927 | debug | (23403) Saving data for station: 70:ee:50:12:78:d0 and measure: rain
netatmo-crawler.0 | 2020-07-02 19:25:50.876 | debug | (23403) Saving data for station: 70:ee:50:12:78:d0 and measure: temperature
netatmo-crawler.0 | 2020-07-02 19:25:50.737 | info | (23403) Saving station data for station: 1
netatmo-crawler.0 | 2020-07-02 19:25:50.736 | debug | (23403) Body:[{"_id":"70:ee:50:12:78:d0","place":{"location":[8.53483009338379,51.427375793457],"timezone":"Europe/Berlin","country":"DE","altitude":422,"city":"Hochsauerlandkreis","street":"Mittlere
netatmo-crawler.0 | 2020-07-02 19:25:50.608 | info | (23403) Getting data for stationid:70:ee:50:12:78:d0
netatmo-crawler.0 | 2020-07-02 19:25:50.605 | info | (23403) Going to get information for station: 1
netatmo-crawler.0 | 2020-07-02 19:25:50.604 | debug | (23403) Working with stationUrl: https://weathermap.netatmo.com//?zoom=12&type=rain&param=hourly&stationid=70%3Aee%3A50%3A12%3A78%3Ad0&maplayer=Map&lang=undefined
netatmo-crawler.0 | 2020-07-02 19:25:50.603 | debug | (23403) Token:Bearer 52d42bfc1777599b298b456c\|4b157f5a32cd79d1b46d4fb4a2ff10a0
netatmo-crawler.0 | 2020-07-02 19:25:49.973 | info | (23403) config stationNameType: id
netatmo-crawler.0 | 2020-07-02 19:25:49.973 | info | (23403) config stationUrls: https://weathermap.netatmo.com//?zoom=12&type=rain&param=hourly&stationid=70%3Aee%3A50%3A12%3A78%3Ad0&maplayer=Map&lang=undefined
netatmo-crawler.0 | 2020-07-02 19:25:49.944 | info | (23403) starting. Version 0.3.1 in /opt/iobroker/node_modules/iobroker.netatmo-crawler, node: v10.18.1, js-controller: 3.1.4
netatmo-crawler.0 | 2020-07-02 19:25:49.168 | debug | (23403) statesDB connected
netatmo-crawler.0 | 2020-07-02 19:25:49.167 | debug | (23403) States connected to redis: 127.0.0.1:9000
netatmo-crawler.0 | 2020-07-02 19:25:49.148 | debug | (23403) States create System PubSub Client
netatmo-crawler.0 | 2020-07-02 19:25:49.146 | debug | (23403) States create User PubSub Client
netatmo-crawler.0 | 2020-07-02 19:25:49.134 | debug | (23403) Redis States: Use Redis connection: 127.0.0.1:9000
netatmo-crawler.0 | 2020-07-02 19:25:49.132 | debug | (23403) objectDB connected
netatmo-crawler.0 | 2020-07-02 19:25:49.126 | debug | (23403) Objects connected to redis: 127.0.0.1:9001
netatmo-crawler.0 | 2020-07-02 19:25:49.103 | debug | (23403) Objects client initialize lua scripts
netatmo-crawler.0 | 2020-07-02 19:25:49.102 | debug | (23403) Objects create User PubSub Client
netatmo-crawler.0 | 2020-07-02 19:25:49.101 | debug | (23403) Objects create System PubSub Client
netatmo-crawler.0 | 2020-07-02 19:25:49.097 | debug | (23403) Objects client ready ... initialize now
netatmo-crawler.0 | 2020-07-02 19:25:49.062 | debug | (23403) Redis Objects: Use Redis connection: 127.0.0.1:9001
host.iobroker_V41 | 2020-07-02 19:25:48.091 | info | instance system.adapter.netatmo-crawler.0 started with pid 23403
host.iobroker_V41 | 2020-07-02 19:25:48.074 | info | instance scheduled system.adapter.netatmo-crawler.0 3 6,12,15,18 * * *
host.iobroker_V41 | 2020-07-02 19:25:45.058 | info | stopInstance canceled schedule system.adapter.netatmo-crawler.0
host.iobroker_V41 | 2020-07-02 19:25:45.057 | info | stopInstance system.adapter.netatmo-crawler.0 (force=false, process=false)

**Comment by Baenker** [comment]
sehr spanned im log steht der richtig Wert

**Comment by Bart1909** [comment]
Jep, hab den rain_yesterday mit dem Wert von rain_today gespeichert. Klassischer copy/paste Fehler.
Version 0.3.2 sollte jetzt klappen

**Comment by Baenker** [comment]
Teste ich gleich. Danke für Deine Mühe. Darf ich Dir per paypal eine Spende zukommen lassen?

**Comment by Bart1909** [comment]
Gerne!
Ach Quatsch! Ist ja noch ganz am Anfang, da hab ich eher dir zu danken, dass du testest und auch Mühe investierst und den Adapter nicht „in die Ecke wirfst“ 😄

**Comment by Baenker** [comment]
Der Wert passt jetzt. Kann man eigentlich sehen was man noch abfragen könnte? So wäre ja Tagestiefsttemperatur und Tageshöchsttemperatur auch spannende Werte. (Für mich nicht, da ich die Temperatur selber in einen Wetterkasten messe)

Die meiste Arbeit hast Du und dafür würde ich auch Spenden. Kannst ja vielleicht auf der Github Seite einen Spenden-Button einbauen. Machen ja einiges Adapter Entwickler. Und dafür das der Adapter erst am Anfang ist läuft er schon ziemlich rund bei mir. Da habe ich schon schlechtere getestet :-))
