### ISSUE TITLE
What exacly is "rain"

### ISSUE THREAD

**Issue by andreaskoerber** [Bart1909/ioBroker.netatmo-crawler#45]
I understand that the data point "rain" now delivers a "current" value. 
But since it does so in mm, there needs to be a timeframe specified. So what exaclty is given as "rain"? ist it the current amount of rain in mm, extrapolated to a day / an hour?
Is it a measured value - or a prognostic one (e.g. extrapolated to "within the current/next hour/day" or so?

**Comment by backfisch88** [comment]
There is only live data

"rain" shows the current status of this hour

"rain_lasthour" the last hour and so on



the unit is milimetres per square metre over the time parameter in the data point (current hour / day / yesterday / last hour)

**Comment by andreaskoerber** [comment]
Thanks! So "rain" ist mm/m² within the actual hour "so far", i.e. since the last full hour?

**Comment by backfisch88** [comment]
I think it's during the last 60 minutes

**Comment by andreaskoerber** [comment]
Ok, thnks.
What, then, ist "rain_lastHour"?
a. the sum of now-120 min: now-60 mint - calculated anew each (full) minute?
b. the value of 60 minutes UP to the last full hour? - calculated anew each full our?

If it is the latter and "rain" ist sum of all minuted from (now-60min) to now, then one may not add "rain_lastHour" and "rain" etc., because they overlap and revent rain would be overweighted.

Where can I fond the exact definitions of the values the service provides?

**Comment by backfisch88** [comment]
I think A
so now -120 min to now -60 Min


dont know exactly cause the Adapter only parse the data from Netatmo

**Comment by andreaskoerber** [comment]
That's why I asked, whether there is some more exact info available. I don't find it there, either.

**Comment by backfisch88** [comment]
I interpret "rain" as rain of the last 60 minutes
and "rain_lasthour" as rain of the hour BEFORE "rain".
