### ISSUE TITLE
Problems after update to JS.controller 5

### ISSUE THREAD

**Issue by Michaelnorge** [Bart1909/ioBroker.netatmo-crawler#46]
After update to js-contoller 5 (5.0.12) this error stands in the log: 

`<html>
<body>

2023-08-19 09:25:07.388 | warn | Could not work with station 4 - Message: Error: undefined is not a valid state value
-- | -- | --

</body>
</html>`

This error message refers to all stations that are in the settings.

**Comment by Bart1909** [comment]
Hi Michael,

I've upgraded to 5.0.12 for myself but for me, the crawling works well. No error messages.

Which nodejs version are you using?

**Comment by backfisch88** [comment]
5.0.12
node.js:18.17.1
NPM:9.6.7

auch keine Probleme. Hatte bei einer n Fehler. Habe alle gelöscht und nochmal hinzugefügt. Da ging es wieder.

**Comment by Michaelnorge** [comment]
> no problems either. Had an error with one. I deleted all of them and added them again. Then everything worked again.

Ok, will try that first...

**Comment by Michaelnorge** [comment]
> Which nodejs version are you using?

18.6.0

**Comment by Michaelnorge** [comment]
> Hi Michael,
> 
> I've upgraded to 5.0.12 for myself but for me, the crawling works well. No error messages.
> 
> Which nodejs version are you using?

I updated node.js now and deleted all links and added them again like @backfisch88 said.

Now the adapter is working again!

Thanks for helping!
