### ISSUE TITLE
no more crawling without authentication

### ISSUE THREAD

**Issue by passuff** [Bart1909/ioBroker.netatmo-crawler#48]
I think netamto changed something so it is currently not possible to crawl stations or the map without authentication.
Please confirm if you are affected too.

**Comment by rtwl21** [comment]
confirmed - no more crawls 
`
netatmo-crawler.0 | 2023-12-04 21:45:18.135 | warn | Could not work with station 2 - Message: Did not get any values for station xx:xx:xx:2a:d3:ec
`

``
netatmo-crawler.0 | 2023-12-04 21:45:16.655 | warn | Could not work with station 1 - Message: Did not get any values for station xx:xx:xx:65:32:32
``

**Comment by Bart1909** [comment]
Will have a look at it tomorrow

**Comment by Bart1909** [comment]
Either it is a general problem, as the official map doesn't show any stations and gets 403 too, or they disabled the public stations.

Does anyone of you (@passuff, @rtwl21) owns a netatmo station and can check, if the map (with other stations than yours) is available if logged in?

**Comment by passuff** [comment]
I've just created an account even though I don't own a station. map is
showing stations and links are working.
When I use links without prior authentication, I get forwarded to the login
page.
Case seems clear. Just the question if it stays like this forever...

Tobi ***@***.***> schrieb am Di., 5. Dez. 2023, 06:54:

**Comment by Bart1909** [comment]
Ah correct, created an account too and with this, it is working fine.
So it should work without owning a station. 

I will wait a little bit if it stays and then will try to find a way to do the login precedure in the adapter.

**Comment by passuff** [comment]
Take over the login/ auth/token functionality from Netatmo (non crawler)
adapter. It's maybe easier to do the copy cat than trying to reinvent the
wheel.

Tobi ***@***.***> schrieb am Di., 5. Dez. 2023, 07:53:

**Comment by passuff** [comment]
I can confirm - everything is working again!

Tobi ***@***.***> schrieb am Mi., 6. Dez. 2023, 13:56:

**Comment by Bart1909** [comment]
Fine! So just a hick up :)
