### ISSUE TITLE
Netatmo need register / Login

### ISSUE THREAD

**Issue by softwarecrash** [Bart1909/ioBroker.netatmo-crawler#49]
today i noticed that the netatmo-crawler dont get new data.
by checking the station on the map it will be redirected to a login, any way to fix that or update the adapter?

**Comment by unstressable** [comment]
same issue here.
There will be the need to create an account and upgrade the adapter.

**Comment by schrecki3000** [comment]
Same here, i think a developer Account is needed from now on, data is not public anymore.

**Comment by Bart1909** [comment]
Yes, seems that the API is not public anymore.

Currently, I've no time for restructuring the Adapter to include the Authentication.

If someone is willing to support this, feel free!

**Comment by Bart1909** [comment]
> just take a short look at the api documantation, this seems not up to date, it based actual on the not longer accessible public api, so i think need to wait to update the api documenatation or ask netatmo for actual information

yes, saw this also. 
In addition you can "try out" the endpoints without adding authentication but then fail with "missing token" error.

And I do not know if you will need a netatmo device to create an API account.

I think, we will have to wait first

**Comment by softwarecrash** [comment]
> > just take a short look at the api documantation, this seems not up to date, it based actual on the not longer accessible public api, so i think need to wait to update the api documenatation or ask netatmo for actual information
> 
> yes, saw this also. In addition you can "try out" the endpoints without adding authentication but then fail with "missing token" error.
> 
> And I do not know if you will need a netatmo device to create an API account.
> 
> I think, we will have to wait first

i will try to ask netatmo support whats going on or what is planed when i find time.
when it only a dev account and a needed token i can try to modify it when it avaible again in the dev portal

**Comment by Diginix** [comment]
These are the log entries I get every 5 min.
```
2024-06-04 15:15:14.751	error	Error while running Netatmo Crawler. Error Message:No authorization token found
2024-06-04 15:15:15.338	error	instance system.adapter.netatmo-crawler.0 terminated with code 15 (UNKNOWN_ERROR)
```
I will disable the instance for now.

**Comment by mggt3** [comment]
It looks like [https://dev.netatmo.com/](https://dev.netatmo.com/) is online again. I just created an account and I am able to see the weather stations at [https://weathermap.netatmo.com/](https://weathermap.netatmo.com/). 
Unfortunately, I can't help with the programming, but I can help with the testing.

**Comment by Bart1909** [comment]
> it looks like the map and data are beeing online again, doesnt need a token or account to retrive data. i think it can close?

seems that they are working on it. I can open the map but not all stations are loading, also with "wrong token" errors.

maybe it will work later?

**Comment by softwarecrash** [comment]
> > it looks like the map and data are beeing online again, doesnt need a token or account to retrive data. i think it can close?
> 
> seems that they are working on it. I can open the map but not all stations are loading, also with "wrong token" errors.
> 
> maybe it will work later?

yes, it looks they working on it, my try with the adapter was succesfull, i can retrive data

**Comment by mggt3** [comment]
It hasn't worked for me yet. I will continue to monitor it.

**Comment by gonzokalle** [comment]
Kurz habe ich wieder Daten bekommen.
Jetzt kommen keine Daten mehr.

<html>
<body>

2024-06-05 15:48:03.102 - info: netatmo-crawler.0 (49912) No body:{"error":{"code":2,"message":"Invalid access_token"}}
--
2024-06-05 15:48:03.115 - warn: netatmo-crawler.0 (49912) Could not work with station 1 - Message: Did not get any values for station 70:ee:50:2c:76:04
2024-06-05 15:48:03.117 - info: netatmo-crawler.0 (49912) Getting data for stationid:70:ee:50:32:af:d2
2024-06-05 15:48:08.933 - error: alexa2.0 (30839) G2A0WK0493830BS4 Error getting equalizer enabled: Error: Timeout
2024-06-05 15:48:13.250 - info: netatmo-crawler.0 (49912) No body:{"error":{"code":2,"message":"Invalid access_token"}}
2024-06-05 15:48:13.267 - info: netatmo-crawler.0 (49912) Got no station data. Trying again
2024-06-05 15:48:14.268 - info: netatmo-crawler.0 (49912) Getting data for stationid:70:ee:50:32:af:d2


</body>
</html>

**Comment by Diginix** [comment]
Again broken without token.

**Comment by Anderl4524** [comment]
Nope - here it dont work :-(

**Comment by Diginix** [comment]
After some hours with stopped instance i'm getting values for 1 of 3 stations without token error in log. The two other stations remains on 20 hours old values.

**Comment by Itsme456** [comment]
I can come up with another symptom:
After restarting the adapter, the data retrieval works exactly once.
Every time I try again, I get the ‘invalid token’ error message.

Perhaps the tokens are now only valid for a short time?

**Comment by softwarecrash** [comment]
> I can come up with another symptom: After restarting the adapter, the data retrieval works exactly once. Every time I try again, I get the ‘invalid token’ error message.
> 
> Perhaps the tokens are now only valid for a short time?

actual the adapter doenst use tokens, so it cant valid for any time.

**Comment by Bart1909** [comment]
> > I can come up with another symptom: After restarting the adapter, the data retrieval works exactly once. Every time I try again, I get the ‘invalid token’ error message.
> > Perhaps the tokens are now only valid for a short time?
> 
> actual the adapter doenst use tokens, so it cant valid for any time.

the adapter uses the public token which was written in the website files itself before

**Comment by Itsme456** [comment]
Yes, the adapter first retrieves the token from the website.
Is it then saved for the next access?

This is how I interpreted the getAuthorisationToken() function.

I could be wrong, I just had a quick look at the source code.
Sorry, I should have reduced the cycle time of the adapter first to verify my idea.
I can't do that from here.
However, restarting the adapter gave me new data again. That was the first one since the last restart last night.

**Comment by gonzokalle** [comment]
I opened the page https://weathermap.netatmo.com/ and restarted the adapter.
I have been getting the data every 5 minutes for an hour and a half.

**Comment by Bart1909** [comment]
Yes, seems to work again.

The Website is also working fine again.

Will close this issue for now
