### ISSUE TITLE
Logging unter Info reduzieren

### ISSUE THREAD

**Issue by Baenker** [Bart1909/ioBroker.netatmo-crawler#6]
Mit jeden Aufruf loggt der Adapter unter Info einige Daten, die das Log unnötig füllen. Besonders wenn der Adapter alle 5 Minuten die Daten abruft. 

1 host.iobroker_V41 | 2020-07-03 06:03:03.763 | info | instance system.adapter.netatmo-crawler.0 terminated with code 0 (NO_ERROR)
-- | -- | -- | --
2 netatmo-crawler.0 | 2020-07-03 06:03:03.250 | info | (2971) Terminated (NO_ERROR): Without reason
3 netatmo-crawler.0 | 2020-07-03 06:03:02.629 | info | (2971) Saving station data for station: 1
4 netatmo-crawler.0 | 2020-07-03 06:03:02.499 | info | (2971) Getting data for stationid:70:ee:50:12:78:d0
5 netatmo-crawler.0 | 2020-07-03 06:03:02.496 | info | (2971) Going to get information for station: 1
6 netatmo-crawler.0 | 2020-07-03 06:03:01.820 | info | (2971) config stationNameType: id
7 netatmo-crawler.0 | 2020-07-03 06:03:01.820 | info | (2971) config stationUrls:  https://weathermap.netatmo.com//?zoom=12&type=rain&param=hourly&stationid=70%3Aee%3A50%3A12%3A78%3Ad0&maplayer=Map&lang=undefined
8 netatmo-crawler.0 | 2020-07-03 06:03:01.797 | info | (2971) starting. Version 0.3.2 in /opt/iobroker/node_modules/iobroker.netatmo-crawler, node: v10.18.1, js-controller: 3.1.4
9 host.iobroker_V41 | 2020-07-03 06:03:00.021 | info | instance system.adapter.netatmo-crawler.0 started with pid 2971

Da der JS-Controller das beenden (1) meldet kann 2 entfallen  (bzw auf debug) wenn Terminated (NO_ERROR): Without reason

3 sollte auf debug geändert werden
4 ok
5 auf debug da es die Ausgabe 4 gibt
6 Zeigt die Config an, kann auf debug
7 zeigt die Config an, kann auf debug
8 ok

**Comment by Bart1909** [comment]
In 0.3.3 eingebaut
