### ISSUE TITLE
Daten anlegen

### ISSUE THREAD

**Issue by sigi2345** [Bart1909/ioBroker.netatmo-crawler#7]
Hallo, sollten nicht Objekte angelegt werden?
Wie funktioniert er?

**Comment by Bart1909** [comment]
Hallo @sigi2345 
hast du dir die Anleitung angeschaut?
Du musst in der Instanz die Wetterstationen eintragen, von denen du die Daten haben willst. Dann werden deren Datenpunkte unter Objekte angelegt

**Comment by sigi2345** [comment]
> Hallo @sigi2345
> hast du dir die Anleitung angeschaut?

Natürlich

> Du musst in der Instanz die Wetterstationen eintragen, von denen du die Daten haben willst. Dann werden deren Datenpunkte unter Objekte angelegt

Habe ich

`

netatmo-crawler.0 | 2020-07-17 13:16:21.738 | info | (19728) Terminated (NO_ERROR): Without reason
-- | -- | -- | --
netatmo-crawler.0 | 2020-07-17 13:16:21.737 | debug | (19728) all done, exiting
netatmo-crawler.0 | 2020-07-17 13:16:21.737 | debug | (19728) Token:Bearer 52d42bfc1777599b298b456c\|4b157f5a32cd79d1b46d4fb4a2ff10a0
netatmo-crawler.0 | 2020-07-17 13:16:21.106 | debug | (19728) Going to save station information with: counter
netatmo-crawler.0 | 2020-07-17 13:16:21.106 | debug | (19728) config stationUrls: https://weathermap.netatmo.com/?zoom=13&type=temp&param=NoFilter&maplayer=Dark&lat=48.11574079168414&lng=14.255447387695314&lang=undefined
netatmo-crawler.0 | 2020-07-17 13:16:21.088 | info | (19728) starting. Version 0.3.4 in C:/Program Files/iobroker/Test/node_modules/iobroker.netatmo-crawler, node: v12.18.0, js-controller: 3.1.6
netatmo-crawler.0 | 2020-07-17 13:16:20.911 | debug | (19728) statesDB connected
netatmo-crawler.0 | 2020-07-17 13:16:20.911 | debug | (19728) States connected to redis: 127.0.0.1:9000
netatmo-crawler.0 | 2020-07-17 13:16:20.893 | debug | (19728) States create System PubSub Client
netatmo-crawler.0 | 2020-07-17 13:16:20.892 | debug | (19728) States create User PubSub Client
netatmo-crawler.0 | 2020-07-17 13:16:20.881 | debug | (19728) Redis States: Use Redis connection: 127.0.0.1:9000
netatmo-crawler.0 | 2020-07-17 13:16:20.880 | debug | (19728) objectDB connected
netatmo-crawler.0 | 2020-07-17 13:16:20.876 | debug | (19728) Objects connected to redis: 127.0.0.1:9013
netatmo-crawler.0 | 2020-07-17 13:16:20.858 | debug | (19728) Objects client initialize lua scripts
netatmo-crawler.0 | 2020-07-17 13:16:20.857 | debug | (19728) Objects create User PubSub Client
netatmo-crawler.0 | 2020-07-17 13:16:20.857 | debug | (19728) Objects create System PubSub Client
netatmo-crawler.0 | 2020-07-17 13:16:20.841 | debug | (19728) Objects client ready ... initialize now
netatmo-crawler.0 | 2020-07-17 13:16:20.813 | debug | (19728) Redis Objects: Use Redis connection: 127.0.0.1:9013
netatmo-crawler.0 | 2020-07-17 13:15:01.988 | info | (14224) Terminated (NO_ERROR): Without reason

`

**Comment by Bart1909** [comment]
Die URL der Station scheint falsch zu sein.
Da muss ein stationid= drin enthalten sein.
Schau mal in der Anleitung, du musst über den "Teilen" Link gehen.
So findet er keine Station-ID mit der er arbeiten kann und macht dann halt nichts

**Comment by sigi2345** [comment]
> Die URL der Station scheint falsch zu sein.
> Da muss ein stationid= drin enthalten sein.
> Schau mal in der Anleitung, du musst über den "Teilen" Link gehen.
> So findet er keine Station-ID mit der er arbeiten kann und macht dann halt nichts

Kann geschlossen werden. Danke.

**Comment by Bart1909** [comment]
Also klappt es jetzt, mit der anderen URL?

**Comment by sigi2345** [comment]
> Also klappt es jetzt, mit der anderen URL?

Ja 👍

**Comment by Bart1909** [comment]
Okay, super :-)
