### ISSUE TITLE
Adapter in ioBroker Adapter Liste aufnehmen

### ISSUE THREAD

**Issue by Baenker** [Bart1909/ioBroker.netatmo-crawler#9]
Mal ein kurzes Feedback von mir. Der Adapter läuft ja jetzt schon einige Wochen bei mir absolut fehlerfrei, problemlos und unauffällig. Ich hole die Daten allerdings nur alle 3 Stunden und Nachts garnicht ab. Für meine Zwecke reicht das.

Wenn ich mich nicht täusche taucht der Adapter nicht in der ioBroker Liste der verfügbaren Adapter auf? Ist das noch geplant?

Habe gerade erst gesehen das es die Version 0.34 gibt. Ich habe die ganze Zeit noch die 0.33 genutzt...

**Comment by Bart1909** [comment]
Hi @Baenker 
Vielen Dank für das Feedback!

Ja, das ist noch geplant. Wir warten nur seit Wochen darauf, dass wir mal ins Latest-Repository kommen, aber irgendwie haben die uns vergessen oder so :-D
Aber wir streben das auf jeden Fall an, später dann auch ins normale Repository.

Viele Grüße 
Bart19 / Tobi

**Comment by backfisch88** [comment]
Seit heute drin
